<?php

declare(strict_types=1);

namespace Dbp\Relay\BasePersonConnectorCampusonlineBundle\EventSubscriber;

use Dbp\Relay\BasePersonBundle\Entity\Person;
use Dbp\Relay\BasePersonConnectorCampusonlineBundle\Event\PersonPostEvent;
use Dbp\Relay\BasePersonConnectorCampusonlineBundle\Event\PersonPreEvent;
use Dbp\Relay\BasePersonConnectorCampusonlineBundle\Service\PersonProvider;
use Dbp\Relay\CoreBundle\LocalData\AbstractLocalDataEventSubscriber;
use Dbp\Relay\CoreBundle\LocalData\LocalDataPostEvent;

class PersonEventSubscriber extends AbstractLocalDataEventSubscriber
{
    public const EMPLOYEE_POSTAL_ADDRESS_SOURCE_ATTRIBUTE = 'employeePostalAddress';
    public const EMPLOYEE_WORK_ADDRESS_SOURCE_ATTRIBUTE = 'employeeWorkAddress';
    public const EMPLOYEE_BUSINESS_CARD_URL_SOURCE_ATTRIBUTE = 'employeeBusinessCardUrl';
    public const EMPLOYEE_MOBILE_PHONE_NUMBER_SOURCE_ATTRIBUTE = 'employeeMobilePhoneNumber';
    public const EMPLOYEE_EXTERNAL_PHONE_NUMBER_SOURCE_ATTRIBUTE = 'employeeExternalPhoneNumber';
    public const EMPLOYEE_INTERNAL_PHONE_NUMBERS_SOURCE_ATTRIBUTE = 'employeeInternalPhoneNumbers';
    public const EMPLOYEE_HOMEPAGE_URL_SOURCE_ATTRIBUTE = 'employeeHomepageUrl';
    public const EMPLOYEE_ADDITIONAL_INFORMATION_SOURCE_ATTRIBUTE = 'employeeAdditionalInformation';
    public const EMPLOYEE_OFFICE_HOURS_SOURCE_ATTRIBUTE = 'employeeOfficeHours';

    protected static function getSubscribedEventNames(): array
    {
        return [
            PersonPreEvent::class,
            PersonPostEvent::class,
        ];
    }

    public function __construct(private readonly PersonProvider $personProvider)
    {
        parent::__construct('BasePerson');
    }

    protected function getAttributeValue(LocalDataPostEvent $postEvent, array $attributeMapEntry): mixed
    {
        $person = $postEvent->getEntity();
        assert($person instanceof Person);
        $personIdentifier = $person->getIdentifier();

        switch ($attributeMapEntry[self::SOURCE_ATTRIBUTE_KEY]) {
            case self::EMPLOYEE_POSTAL_ADDRESS_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getEmployeePostalAddress($personIdentifier);
            case self::EMPLOYEE_WORK_ADDRESS_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getEmployeeWorkAddress($personIdentifier);
            case self::EMPLOYEE_BUSINESS_CARD_URL_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getPersonFromApiCached($personIdentifier)->getBusinessCardUrlEmployee();
            case self::EMPLOYEE_MOBILE_PHONE_NUMBER_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getPersonFromApiCached($personIdentifier)->getMobilePhoneNumberEmployee();
            case self::EMPLOYEE_EXTERNAL_PHONE_NUMBER_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getPersonFromApiCached($personIdentifier)->getExternalPhoneNumberEmployee();
            case self::EMPLOYEE_INTERNAL_PHONE_NUMBERS_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getPersonFromApiCached($personIdentifier)->getInternalPhoneNumbersEmployee();
            case self::EMPLOYEE_HOMEPAGE_URL_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getPersonFromApiCached($personIdentifier)->getWwwHomepageEmployee();
            case self::EMPLOYEE_ADDITIONAL_INFORMATION_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getPersonFromApiCached($personIdentifier)->getAdditionalInformation();
            case self::EMPLOYEE_OFFICE_HOURS_SOURCE_ATTRIBUTE:
                $this->personProvider->requestCacheCurrentResultPersons();

                return $this->personProvider->getPersonFromApiCached($personIdentifier)->getOfficeHoursEmployee();
        }

        return parent::getAttributeValue($postEvent, $attributeMapEntry); // TODO: Change the autogenerated stub
    }
}
